ALTER TABLE "petshop"."product_prices" ALTER COLUMN "price" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."product_uom_conversions" ALTER COLUMN "ratio" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."product_uom_conversions" ALTER COLUMN "weight_gram" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."products" ALTER COLUMN "weight_gram" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."product_stock_batches" ALTER COLUMN "qty_received" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."product_stock_batches" ALTER COLUMN "qty_remaining" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."product_stock_batches" ALTER COLUMN "cost_price" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."product_stocks" ALTER COLUMN "qty" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."stock_adjustments" ALTER COLUMN "previous_qty" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."stock_adjustments" ALTER COLUMN "new_qty" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."stock_auto_breaks" ALTER COLUMN "qty_broken" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."stock_auto_breaks" ALTER COLUMN "qty_gained" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."open_bills" ALTER COLUMN "total_amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."transaction_items" ALTER COLUMN "qty" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."transaction_items" ALTER COLUMN "unit_price" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."transaction_items" ALTER COLUMN "total_price" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."transaction_items" ALTER COLUMN "discount_amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."transaction_items" ALTER COLUMN "cogs" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."transaction_payments" ALTER COLUMN "amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."transactions" ALTER COLUMN "total_amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."transactions" ALTER COLUMN "discount_amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."transactions" ALTER COLUMN "tax_amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."transactions" ALTER COLUMN "payable_amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."transactions" ALTER COLUMN "paid_amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."transactions" ALTER COLUMN "change_amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."shift_cashier_breakdown" ALTER COLUMN "total_sales_cash" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."shift_cashier_breakdown" ALTER COLUMN "total_sales_qris" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."shift_cashier_breakdown" ALTER COLUMN "total_sales_debit" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."shift_cashier_breakdown" ALTER COLUMN "total_sales_credit" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."shift_cashier_breakdown" ALTER COLUMN "total_sales_debt" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."shift_cashier_breakdown" ALTER COLUMN "total_sales" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."shift_cashier_breakdown" ALTER COLUMN "total_expenses" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."shift_cashier_breakdown" ALTER COLUMN "modal_share" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."shift_cashier_breakdown" ALTER COLUMN "expected_cash" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."shift_cashier_breakdown" ALTER COLUMN "real_cash" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."shift_cashier_breakdown" ALTER COLUMN "variance" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."shift_expenses" ALTER COLUMN "amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."shifts" ALTER COLUMN "opening_cash" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."shifts" ALTER COLUMN "total_closing_cash_real" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."shifts" ALTER COLUMN "total_closing_cash_expected" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."shifts" ALTER COLUMN "total_variance" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."po_receiving_items" ALTER COLUMN "qty_received" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."po_receiving_items" ALTER COLUMN "qty_damaged" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."purchase_order_items" ALTER COLUMN "qty_ordered" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."purchase_order_items" ALTER COLUMN "qty_received" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."purchase_order_items" ALTER COLUMN "qty_damaged" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."purchase_order_items" ALTER COLUMN "unit_cost" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."purchase_order_items" ALTER COLUMN "invoice_unit_cost" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."purchase_orders" ALTER COLUMN "total_amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."supplier_payable_payments" ALTER COLUMN "amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."supplier_payables" ALTER COLUMN "total_amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."supplier_payables" ALTER COLUMN "paid_amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."stock_opname_items" ALTER COLUMN "system_qty" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."stock_opname_items" ALTER COLUMN "physical_qty" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."stock_opname_items" ALTER COLUMN "variance_qty" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."stock_opname_items" ALTER COLUMN "variance_cost_value" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."stock_opname_items" ALTER COLUMN "recount_physical_qty" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."promotions" ALTER COLUMN "value" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."promotions" ALTER COLUMN "min_purchase" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."promotions" ALTER COLUMN "max_discount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."customer_debts" ALTER COLUMN "total_amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."customer_debts" ALTER COLUMN "paid_amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."customer_debts" ALTER COLUMN "remaining_amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."debt_payments" ALTER COLUMN "amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."owner_price_overrides" ALTER COLUMN "original_price" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."owner_price_overrides" ALTER COLUMN "overridden_price" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."damaged_goods" ALTER COLUMN "total_loss_value" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."damaged_goods_items" ALTER COLUMN "qty" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."damaged_goods_items" ALTER COLUMN "cost_price" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."damaged_goods_items" ALTER COLUMN "loss_value" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."delivery_orders" ALTER COLUMN "total_weight_gram" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."return_items" ALTER COLUMN "qty" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."return_items" ALTER COLUMN "unit_price" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."return_items" ALTER COLUMN "cogs" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."return_items" ALTER COLUMN "refund_amount" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "petshop"."returns" ALTER COLUMN "total_refund_amount" SET DATA TYPE integer;